/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package hwr.berlin;

import java.io.File;
import java.io.IOException;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

//import org.testng.collections.Lists;

/**
 *
 * @author joemi
 * @param <CardLayout>
 */
public class GuiBuild<CardLayout> extends javax.swing.JFrame {

    /**
     * Creates new form GuiBuild
     */
    
    public GuiBuild() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cards = new javax.swing.JPanel();
        startWindow = new javax.swing.JPanel();
        butStartBuchLaden = new javax.swing.JButton();
        butStartBuchNeu = new javax.swing.JButton();
        kontaktAnlegen = new javax.swing.JPanel();
        textFieldNameNeu = new javax.swing.JTextField();
        textFieldAdresseNeu = new javax.swing.JTextField();
        textFieldeMailNeu = new javax.swing.JTextField();
        textfieldNummerNeu = new javax.swing.JTextField();
        labelNameNeu = new javax.swing.JLabel();
        labelAdresseNeu = new javax.swing.JLabel();
        labelEMailNeu = new javax.swing.JLabel();
        labelNummerNeu = new javax.swing.JLabel();
        butSpeichernNeu = new javax.swing.JButton();
        butZusNummerNeu = new javax.swing.JButton();
        butCancelNeu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBeschreibungNeu = new javax.swing.JTextField();
        neueNummer2 = new javax.swing.JLabel();
        textfieldNeueNummer2 = new javax.swing.JTextField();
        neueBeschreibung2 = new javax.swing.JLabel();
        neueNummer3 = new javax.swing.JLabel();
        neueBeschreibung3 = new javax.swing.JLabel();
        neueNummer4 = new javax.swing.JLabel();
        neueBeschreibung4 = new javax.swing.JLabel();
        textfieldBeschreibung2 = new javax.swing.JTextField();
        textfieldNeueNummer3 = new javax.swing.JTextField();
        textfieldBeschreibung3 = new javax.swing.JTextField();
        textfieldNeueNummer4 = new javax.swing.JTextField();
        textfieldBeschreibung4 = new javax.swing.JTextField();
        alleKontakteAnzeigen = new javax.swing.JPanel();
        listNamen = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        butKontaktSuchen = new javax.swing.JButton();
        butKontaktLoeschen = new javax.swing.JButton();
        detailsName = new javax.swing.JLabel();
        detailsAdresse = new javax.swing.JLabel();
        detailsEmail = new javax.swing.JLabel();
        detailsNummer = new javax.swing.JLabel();
        detailsNameText = new javax.swing.JTextField();
        detailsAdresseText = new javax.swing.JTextField();
        detailsEmailText = new javax.swing.JTextField();
        butKontaktSpeichern = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNummern = new javax.swing.JTextArea();
        panelKontaktSuchen = new javax.swing.JPanel();
        textSuche = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonName = new javax.swing.JRadioButton();
        jRadioButtonAdresse = new javax.swing.JRadioButton();
        jRadioButtonEmailSuche = new javax.swing.JRadioButton();
        jRadioButtonNummer = new javax.swing.JRadioButton();
        jButtonSuchen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSuchergebnisse = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabelSucheDetailsName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSucheDetailsName = new javax.swing.JTextField();
        jTextFieldSucheDetailsAdresse = new javax.swing.JTextField();
        jTextFieldSucheDetailsEmail = new javax.swing.JTextField();
        jTextFieldSucheDetailsNummer = new javax.swing.JTextField();
        butSucheZuruck = new javax.swing.JButton();
        menueleiste = new javax.swing.JMenuBar();
        menuTelefonbuch = new javax.swing.JMenu();
        menuLaden = new javax.swing.JMenuItem();
        menuSpeichern = new javax.swing.JMenuItem();
        menuBeenden = new javax.swing.JMenuItem();
        menuKontakt = new javax.swing.JMenu();
        menuNeuerKontakt = new javax.swing.JMenuItem();
        menuAlleKontakteAnzeigen = new javax.swing.JMenuItem();
        menuKontaktSuchen = new javax.swing.JMenuItem();
        menuKontaktLoeschen = new javax.swing.JMenuItem();
        telefonbuch = new Telefonbuch();
        suchergebnisse = new Telefonbuch();
        neueNummer = new Telefonnummer();
        fehlermeldung = new javax.swing.JOptionPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cards.setLayout(new java.awt.CardLayout());

        butStartBuchLaden.setText("Telefonbuch laden");
        butStartBuchLaden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStartBuchLadenActionPerformed(evt);
            }
        });

        butStartBuchNeu.setText("Neues Telefonbuch anlegen");
        butStartBuchNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStartBuchNeuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startWindowLayout = new javax.swing.GroupLayout(startWindow);
        startWindow.setLayout(startWindowLayout);
        startWindowLayout.setHorizontalGroup(
            startWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startWindowLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(butStartBuchLaden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addComponent(butStartBuchNeu)
                .addGap(121, 121, 121))
        );
        startWindowLayout.setVerticalGroup(
            startWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startWindowLayout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addGroup(startWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butStartBuchLaden)
                    .addComponent(butStartBuchNeu))
                .addGap(83, 83, 83))
        );

        cards.add(startWindow, "cardStartWindow");

        kontaktAnlegen.setAutoscrolls(true);
        java.awt.GridBagLayout kontaktAnlegenLayout1 = new java.awt.GridBagLayout();
        kontaktAnlegenLayout1.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        kontaktAnlegenLayout1.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        kontaktAnlegen.setLayout(kontaktAnlegenLayout1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        kontaktAnlegen.add(textFieldNameNeu, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        kontaktAnlegen.add(textFieldAdresseNeu, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 177;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        kontaktAnlegen.add(textFieldeMailNeu, gridBagConstraints);


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        kontaktAnlegen.add(textfieldNummerNeu, gridBagConstraints);

        labelNameNeu.setText("Nachname, Vorname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        kontaktAnlegen.add(labelNameNeu, gridBagConstraints);

        labelAdresseNeu.setText("Adresse (Straße, NR, PLZ, Ort)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 1.0;
        kontaktAnlegen.add(labelAdresseNeu, gridBagConstraints);

        labelEMailNeu.setText("e-Mail Adresse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 167;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        kontaktAnlegen.add(labelEMailNeu, gridBagConstraints);

        labelNummerNeu.setText("Telefonnummer #1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 158;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        kontaktAnlegen.add(labelNummerNeu, gridBagConstraints);

        butSpeichernNeu.setText("Speichern");
        butSpeichernNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSpeichernNeuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        kontaktAnlegen.add(butSpeichernNeu, gridBagConstraints);

        butZusNummerNeu.setText("zusätzliche Telefonnummer");
        butZusNummerNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butZusNummerNeuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        kontaktAnlegen.add(butZusNummerNeu, gridBagConstraints);

        butCancelNeu.setText("Zurück");
        butCancelNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelNeuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        kontaktAnlegen.add(butCancelNeu, gridBagConstraints);

        jLabel1.setText("Beschreibung ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(jLabel1, gridBagConstraints);


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(jTextFieldBeschreibungNeu, gridBagConstraints);

        neueNummer2.setText("Telefonnummer #2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(neueNummer2, gridBagConstraints);


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(textfieldNeueNummer2, gridBagConstraints);

        neueBeschreibung2.setText("Beschreibung #2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(neueBeschreibung2, gridBagConstraints);

        neueNummer3.setText("Telefonnummer #3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(neueNummer3, gridBagConstraints);

        neueBeschreibung3.setText("Beschreibung #3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(neueBeschreibung3, gridBagConstraints);

        neueNummer4.setText("Telefonnummer #4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(neueNummer4, gridBagConstraints);

        neueBeschreibung4.setText("Beschreibung #4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(neueBeschreibung4, gridBagConstraints);


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(textfieldBeschreibung2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(textfieldNeueNummer3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(textfieldBeschreibung3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(textfieldNeueNummer4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        kontaktAnlegen.add(textfieldBeschreibung4, gridBagConstraints);

        // Felder Zusätzliche Nummern + Beschreibung unsichtbar per Default, werden sichtbar durch klick auf Button "zusätzliche Nummer"
            neueNummer2.setVisible(false);
            neueBeschreibung2.setVisible(false);
            textfieldBeschreibung2.setVisible(false);
            textfieldNeueNummer2.setVisible(false);

        neueNummer3.setVisible(false);
        neueBeschreibung3.setVisible(false);
        textfieldBeschreibung3.setVisible(false);
        textfieldNeueNummer3.setVisible(false);

        neueNummer4.setVisible(false);
        neueBeschreibung4.setVisible(false);
        textfieldBeschreibung4.setVisible(false);
        textfieldNeueNummer4.setVisible(false);
        


        cards.add(kontaktAnlegen, "cardKontaktAnlegen");

        jList1.setModel(jList1.getModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        listNamen.setViewportView(jList1);

        butKontaktSuchen.setText("Suchen");
        butKontaktSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKontaktSuchenActionPerformed(evt);
            }
        });

        butKontaktLoeschen.setText("Kontakt Löschen");
        butKontaktLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKontaktLoeschenActionPerformed(evt);
            }
        });

        detailsName.setText("Name");

        detailsAdresse.setText("Adresse");

        detailsEmail.setText("E-Mail");

        detailsNummer.setText("Telefonnummer");



        butKontaktSpeichern.setText("Kontakt speichern");
        butKontaktSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKontaktSpeichernActionPerformed(evt);
            }
        });

        jTextAreaNummern.setColumns(8);
        jTextAreaNummern.setRows(3);
        jScrollPane2.setViewportView(jTextAreaNummern);

        javax.swing.GroupLayout alleKontakteAnzeigenLayout = new javax.swing.GroupLayout(alleKontakteAnzeigen);
        alleKontakteAnzeigen.setLayout(alleKontakteAnzeigenLayout);
        alleKontakteAnzeigenLayout.setHorizontalGroup(
            alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alleKontakteAnzeigenLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(listNamen, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alleKontakteAnzeigenLayout.createSequentialGroup()
                        .addComponent(detailsNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(alleKontakteAnzeigenLayout.createSequentialGroup()
                                .addComponent(butKontaktSpeichern)
                                .addGap(18, 18, 18)
                                .addComponent(butKontaktLoeschen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(alleKontakteAnzeigenLayout.createSequentialGroup()
                        .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detailsName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detailsAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detailsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detailsAdresseText)
                            .addComponent(detailsEmailText)
                            .addComponent(detailsNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butKontaktSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        alleKontakteAnzeigenLayout.setVerticalGroup(
            alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alleKontakteAnzeigenLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(listNamen, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(alleKontakteAnzeigenLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailsName)
                    .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(detailsNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butKontaktSuchen)))
                .addGap(23, 23, 23)
                .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsAdresse)
                    .addComponent(detailsAdresseText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsEmail)
                    .addComponent(detailsEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alleKontakteAnzeigenLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(detailsNummer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(alleKontakteAnzeigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butKontaktLoeschen)
                    .addComponent(butKontaktSpeichern))
                .addGap(51, 51, 51))
        );

        cards.add(alleKontakteAnzeigen, "cardAlleKontakteAnzeigen");



        jLabel4.setText("Suche:");

        jRadioButtonName.setText("Name");


        jRadioButtonAdresse.setText("Adresse");

        jRadioButtonEmailSuche.setText("E-Mail");

        jRadioButtonNummer.setText("Telefonnummer");

        jButtonSuchen.setText("Suchen");
        jButtonSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuchenActionPerformed(evt);
            }
        });

        jListSuchergebnisse.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSuchergebnisseValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListSuchergebnisse);

        jLabel5.setText("in:");

        jLabelSucheDetailsName.setText("Name");

        jLabel6.setText("Adresse");

        jLabel7.setText("E-Mail");

        jLabel8.setText("Telefonnummer");

        butSucheZuruck.setText("Zurück");
        butSucheZuruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSucheZuruckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKontaktSuchenLayout = new javax.swing.GroupLayout(panelKontaktSuchen);
        panelKontaktSuchen.setLayout(panelKontaktSuchenLayout);
        panelKontaktSuchenLayout.setHorizontalGroup(
            panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                        .addComponent(butSucheZuruck, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSuche, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonEmailSuche, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonNummer))
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSucheDetailsName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSucheDetailsName, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSucheDetailsAdresse)
                                    .addComponent(jTextFieldSucheDetailsEmail)))
                            .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSucheDetailsNummer)))
                        .addGap(49, 49, 49))))
        );
        panelKontaktSuchenLayout.setVerticalGroup(
            panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textSuche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonName)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAdresse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEmailSuche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNummer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSuchen))
                    .addGroup(panelKontaktSuchenLayout.createSequentialGroup()
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSucheDetailsName)
                            .addComponent(jTextFieldSucheDetailsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldSucheDetailsAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldSucheDetailsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKontaktSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSucheDetailsNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(butSucheZuruck)
                .addGap(55, 55, 55))
        );

        cards.add(panelKontaktSuchen, "cardKontaktSuchen");

        menuTelefonbuch.setText("Telefonbuch");

        menuLaden.setText("Telefonbuch laden");
        menuLaden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLadenActionPerformed(evt);
            }
        });
        menuTelefonbuch.add(menuLaden);

        menuSpeichern.setText("Telefonbuch speichern");
        menuSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSpeichernActionPerformed(evt);
            }
        });
        menuTelefonbuch.add(menuSpeichern);

        menuBeenden.setText("Beenden");
        menuBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBeendenActionPerformed(evt);
            }
        });
        menuTelefonbuch.add(menuBeenden);

        menueleiste.add(menuTelefonbuch);

        menuKontakt.setText("Kontakt");

        menuNeuerKontakt.setText("Neuer Kontakt");
        menuNeuerKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNeuerKontaktActionPerformed(evt);
            }
        });
        menuKontakt.add(menuNeuerKontakt);

        menuAlleKontakteAnzeigen.setText("Alle Kontakte anzeigen");
        menuAlleKontakteAnzeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlleKontakteAnzeigenActionPerformed(evt);
            }
        });
        menuKontakt.add(menuAlleKontakteAnzeigen);

        menuKontaktSuchen.setText("Kontakt suchen");
        menuKontaktSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKontaktSuchenActionPerformed(evt);
            }
        });
        menuKontakt.add(menuKontaktSuchen);

        menuKontaktLoeschen.setText("Kontakt löschen");
        menuKontakt.add(menuKontaktLoeschen);

        menueleiste.add(menuKontakt);
        menuKontakt.setEnabled(false);
        setJMenuBar(menueleiste);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    //wie menuLaden
    private void butStartBuchLadenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStartBuchLadenActionPerformed
        //menuLadenActionPerformed lädt das Telefonbuch
        menuLadenActionPerformed(evt);
        }
//GEN-LAST:event_butStartBuchLadenActionPerformed


    //Button Neuer Kontakt -> Speichern
    //Erstellt neuen Kontakt, Zuweisung der Attribute per textfield.getText() und setter Methoden
    //zusNummerCounter zählt wie oft der Button "zusätzliche Nummer" betätigt wurde
    //Anzeige zusätzlicher Felder je nach Wert des Counters
    //Fügt Telefonnummer zu Kontakt hinzu
    //Fügt Kontakt zu Telefonbuch hinzu
    //Resettet danach den Counter und die Eingabefelder und springt zu "Alle Kontakte anzeigen"
    private void butSpeichernNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSpeichernNeuActionPerformed
        int status = 1;
        
        //Neuer Kontakt erstellen
        Kontakt neuerKontakt = new Kontakt();


        neuerKontakt.setName(textFieldNameNeu.getText());
        neuerKontakt.setAdresse(textFieldAdresseNeu.getText());
        neuerKontakt.setEmail(textFieldeMailNeu.getText());

        //Telefonnummer
        neueNummer.stringToTelefonnummer(textfieldNummerNeu.getText());
        neueNummer.setBeschreibung(jTextFieldBeschreibungNeu.getText());

        if (textFieldNameNeu.getText().isEmpty() && status == 1){
            JOptionPane.showMessageDialog(null, "Bitte geben Sie einen Namen ein.");
        }

        if (1 <= zusNummerCounter && zusNummerCounter <4){
            Telefonnummer neueNummer2 = new Telefonnummer();
            neueNummer2.stringToTelefonnummer(textfieldNeueNummer2.getText());
            neueNummer2.setBeschreibung(textfieldBeschreibung2.getText());
            neuerKontakt.fuegeNrHinzu(neueNummer2);
          }

         if (2 <= zusNummerCounter && zusNummerCounter < 4){
            Telefonnummer neueNummer3 = new Telefonnummer();
            neueNummer3.stringToTelefonnummer(textfieldNeueNummer3.getText());
            neueNummer3.setBeschreibung(textfieldBeschreibung3.getText());
            neuerKontakt.fuegeNrHinzu(neueNummer3);
         }      
        
        if (3 <= zusNummerCounter && zusNummerCounter < 4){
            Telefonnummer neueNummer4 = new Telefonnummer();
            neueNummer4.stringToTelefonnummer(textfieldNeueNummer4.getText());
            neueNummer4.setBeschreibung(textfieldBeschreibung4.getText());
            neuerKontakt.fuegeNrHinzu(neueNummer4);
            } 

            //Telefonnummer zu Kontakt hinzufügen
            neuerKontakt.fuegeNrHinzu(neueNummer);

            //Kontakt zu Telefonbuch hinzufügen
            telefonbuch.fuegeKontaktHinzu(neuerKontakt);

            //Textfelder resetten
            status = 0;
            textFieldNameNeu.setText("");
            textFieldAdresseNeu.setText("");
            textFieldeMailNeu.setText("");
            textfieldNummerNeu.setText("");
            jTextFieldBeschreibungNeu.setText("");
            textfieldNeueNummer2.setText("");
            textfieldBeschreibung2.setText("");
            textfieldNeueNummer3.setText("");
            textfieldBeschreibung3.setText("");
            textfieldNeueNummer4.setText("");
            textfieldBeschreibung4.setText("");
            jListFuellen(telefonbuch);
            neueNummer2.setVisible(false);
            neueBeschreibung2.setVisible(false);
            textfieldBeschreibung2.setVisible(false);
            textfieldNeueNummer2.setVisible(false);

            neueNummer3.setVisible(false);
            neueBeschreibung3.setVisible(false);
            textfieldBeschreibung3.setVisible(false);
            textfieldNeueNummer3.setVisible(false);

            neueNummer4.setVisible(false);
            neueBeschreibung4.setVisible(false);
            textfieldBeschreibung4.setVisible(false);
            textfieldNeueNummer4.setVisible(false);
            revalidate();
            repaint();
            //counter resetten
            zusNummerCounter = 0;
            



        CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardAlleKontakteAnzeigen");
    }
        //-> card AllekOntakteanzeigen
    //GEN-LAST:event_butSpeichernNeuActionPerformed

    //mit getSelectedIndex den aktuellen Index abfragen (Kontakt auswählen)
    //Kontakt aus Telefonbuch löschen
    //Felder resetten
    private void butKontaktLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKontaktLoeschenActionPerformed
        // TODO add your handling code here:
                //Auswahl index
        int index = jList1.getSelectedIndex();

        //Kontakt auslesen
        Kontakt details = telefonbuch.telefonbuchArray.get(index);
        
        telefonbuch.loescheKontakt(details);

        detailsNameText.setText("");
        detailsAdresseText.setText("");
        detailsEmailText.setText("");
        jTextAreaNummern.setText("");
        //jList updaten
        jListFuellen(telefonbuch);
    }//GEN-LAST:event_butKontaktLoeschenActionPerformed

    private void menuBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBeendenActionPerformed
        //Programm schließen
        System.out.println("Programm wurde beendet!");
        System.exit(0);
    }//GEN-LAST:event_menuBeendenActionPerformed

    //Füllt und aktualisiert die jList
    //vielleicht überflüssig aber Programm läuft
    private void jListFuellen(Telefonbuch telefonbuch){
        //Befüllt und aktualisiert die jListe
        DefaultListModel<String> model = new DefaultListModel<>();

        for (Kontakt kontakt:telefonbuch.telefonbuchArray){
             model.addElement(kontakt.getName());
        }
        jList1.setModel(model);
    }

    //Öffnet einen Filechooser mit "Telefonbuch" Filter und festgelegtem Ordner (Projektordner)
    //Lädt die ausgewählte Datei als Telefonbuch
    private void menuLadenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLadenActionPerformed
        
        final String filelocation = "telefonbuch/src/main/java/hwr/berlin/Telefonbuch.ser";
        JFileChooser fc = new JFileChooser(filelocation);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Telefonbuch", "ser");  
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(filter);
        int a = fc.showOpenDialog(null);
        
        //Bei Klick auf "Öffnen"
        if (a == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
           
            System.out.println("Telefonbuch wurde geladen!");
            
            telefonbuch.buchLaden(file);

            //Ausgabe in Konsole zur Verifizierung
            telefonbuch.alleKontakteAnzeigen();
           
            //Springe zu "Alle Kontakte anzeigen"
            CardLayout cl = (CardLayout) (cards.getLayout());
            ((java.awt.CardLayout) cl).show(cards, "cardAlleKontakteAnzeigen");

            jListFuellen(telefonbuch);
            //Menupunkt "Kontakt" wird enabled
            menuKontakt.setEnabled(true);
        } 
    }//GEN-LAST:event_menuLadenActionPerformed

    //Öffnet Filechooser mit "Telefonbuch" Filter und festgelegtem Ordner
    private void menuSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSpeichernActionPerformed
        String filelocation = "telefonbuch/src/main/java/hwr/berlin/";                      // Standard Location für File
        JFileChooser fc = new JFileChooser(filelocation);  
        fc.setSelectedFile(new File(filelocation));                         

        //setze Filter auf Typ "Telefonbuch" mit Endung ".ser"
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Telefonbuch", "ser");  
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(filter);

        int a = fc.showSaveDialog(null);
        
        //bei klick auf "Speichern"
        if (a == JFileChooser.APPROVE_OPTION) {
            File outputFile = fc.getSelectedFile();
            String filename = fc.getSelectedFile().getName().toString();
            
            System.out.println("Überprüfe ob "+filename+" existiert...");
            if (!outputFile.exists()) {
                try {
                    //Neue Datei erstellen mit Endung .ser
                    outputFile.createNewFile();
                    if (!filename.endsWith(".ser")) {
                    filename += ".ser";
                }
                   System.out.println("Datei " + filename + " wurde erfolgreich erstellt");
                
                } catch (IOException e) {
                    System.out.println("Fehler beim erstellen einer neuen Datei");
                    //e.printStackTrace();
                }
            }
            //TODO Cancel Button Action1
        
            System.out.println("Versuche zu speichern...");
            telefonbuch.alleKontakteAnzeigen();                 //Bug Hunting

            //Speichern
            telefonbuch.speichern(outputFile);
        }
        System.out.println("Telefonbuch wurde gespeichert!");

    // TODO add your handling code here:
    }//GEN-LAST:event_menuSpeichernActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int index = 0;
        //Auswahl index
        index = jList1.getSelectedIndex();

        //Kontakt auslesen
        Kontakt details = telefonbuch.telefonbuchArray.get(index);

        //Textfelder befüllen
        detailsNameText.setText(details.getName());
        detailsAdresseText.setText(details.getAdresse());
        detailsEmailText.setText(details.getEmail());
        jTextAreaNummern.setText(details.nummernToString());

    }//GEN-LAST:event_jList1ValueChanged


    private void butKontaktSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKontaktSpeichernActionPerformed
        //Kontakt im Telefonbuch ändern
        // TODO add your handling code here:
                //Auswahl index
        int index = jList1.getSelectedIndex();
        //Telefonnummer neueNummer = new Telefonnummer();

        //Kontakt auslesen
        Kontakt details = telefonbuch.telefonbuchArray.get(index);

        details.setName(detailsNameText.getText());
        details.setAdresse(detailsAdresseText.getText());
        details.setEmail(detailsEmailText.getText());
        neueNummer.stringToTelefonnummer(textfieldNummerNeu.getText());
        neueNummer.setBeschreibung(jTextFieldBeschreibungNeu.getText());
        details.fuegeNrHinzu(neueNummer);
        
    }//GEN-LAST:event_butKontaktSpeichernActionPerformed

    //Bei Klick auf Menu "Neuer Kontakt"
    //setze counter auf 0
    //setze zusätliche Felder unsichtbar
    private void menuNeuerKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNeuerKontaktActionPerformed
        // TODO add your handling code here:
        //Springe zu Card "Neuer Kontakt anlegen"
        CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardKontaktAnlegen");
        zusNummerCounter = 0;
        neueNummer2.setVisible(false);
        neueBeschreibung2.setVisible(false);
        textfieldBeschreibung2.setVisible(false);
        textfieldNeueNummer2.setVisible(false);

        neueNummer3.setVisible(false);
        neueBeschreibung3.setVisible(false);
        textfieldBeschreibung3.setVisible(false);
        textfieldNeueNummer3.setVisible(false);

        neueNummer4.setVisible(false);
        neueBeschreibung4.setVisible(false);
        textfieldBeschreibung4.setVisible(false);
        textfieldNeueNummer4.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_menuNeuerKontaktActionPerformed

    //Button Neuer Kontakt -> Zurück
    //Counter und Felder resetten
    //Zu Alle Kontakte anzeigen springen
    private void butCancelNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelNeuActionPerformed
        // TODO add your handling code here:
        //counter resetten
        zusNummerCounter = 0;
        neueNummer2.setVisible(false);
        neueBeschreibung2.setVisible(false);
        textfieldBeschreibung2.setVisible(false);
        textfieldNeueNummer2.setVisible(false);

        neueNummer3.setVisible(false);
        neueBeschreibung3.setVisible(false);
        textfieldBeschreibung3.setVisible(false);
        textfieldNeueNummer3.setVisible(false);

        neueNummer4.setVisible(false);
        neueBeschreibung4.setVisible(false);
        textfieldBeschreibung4.setVisible(false);
        textfieldNeueNummer4.setVisible(false);
        revalidate();
        repaint();
        //Springe zu Card "Alle Kontakte anzeigen"
        CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardAlleKontakteAnzeigen");
    }//GEN-LAST:event_butCancelNeuActionPerformed

    //Button zusätzliche Nummer
    //Bei Klick erscheinen Textfelder für Nummer und Beschreibung
    //Counter zählt wie oft der Button gedrückt wurde
    private void butZusNummerNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butZusNummerNeuActionPerformed
        // TODO add your handling code here:
        zusNummerCounter++;

        if (zusNummerCounter == 1){
            neueNummer2.setVisible(true);
            neueBeschreibung2.setVisible(true);
            textfieldBeschreibung2.setVisible(true);
            textfieldNeueNummer2.setVisible(true);
        }
        if (zusNummerCounter == 2){
            neueNummer3.setVisible(true);
            neueBeschreibung3.setVisible(true);
            textfieldBeschreibung3.setVisible(true);
            textfieldNeueNummer3.setVisible(true);
        }
        if (zusNummerCounter == 3){
            neueNummer4.setVisible(true);
            neueBeschreibung4.setVisible(true);
            textfieldBeschreibung4.setVisible(true);
            textfieldNeueNummer4.setVisible(true);
        }

    }//GEN-LAST:event_butZusNummerNeuActionPerformed

    //Button Kontakt Suchen
    //Springt zu Kontakt suchen
    private void butKontaktSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKontaktSuchenActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardKontaktSuchen");

    }//GEN-LAST:event_butKontaktSuchenActionPerformed

    
    //Menu Kontakt suchen
    private void menuKontaktSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKontaktSuchenActionPerformed
        // TODO add your handling code here:
        //jDialogSuchen.setVisible(true);
        CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardKontaktSuchen");
    }//GEN-LAST:event_menuKontaktSuchenActionPerformed

    private void menuAlleKontakteAnzeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlleKontakteAnzeigenActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardAlleKontakteAnzeigen");
    }//GEN-LAST:event_menuAlleKontakteAnzeigenActionPerformed


    //User kann mittels Radiobutton auswählen wo gesucht werden soll, Mehrfachauswahl möglich
    //Vergleicht input String mit den ausgewählten Feldern
    //if true, fügt Kontakt zu neuen Telefonbuch Suchergebnisse hinzu
    //Telefonbuch Suchergebnisse wird in der jList angezeigt
    private void jButtonSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuchenActionPerformed
        // TODO add your handling code here:
        
        //Kontakt suchErgebnis = new Kontakt();
        DefaultListModel<String> model = new DefaultListModel<>();
        String suchString = textSuche.getText();
       

        for (Kontakt kontakt:telefonbuch.telefonbuchArray){

            if (jRadioButtonName.isSelected()){
                if (kontakt.getName().contains(suchString)){

                    model.addElement(kontakt.getName());
                    suchergebnisse.fuegeKontaktHinzu(kontakt);
                }
            }

            if (jRadioButtonAdresse.isSelected()){
                if (kontakt.getAdresse().contains(suchString)){
                    model.addElement(kontakt.getName());
                    suchergebnisse.fuegeKontaktHinzu(kontakt);
                }
            }

            if (jRadioButtonEmailSuche.isSelected()){
                if(kontakt.getEmail().contains(suchString)){
                    model.addElement(kontakt.getName());
                    suchergebnisse.fuegeKontaktHinzu(kontakt);
                }
            }

            if (jRadioButtonNummer.isSelected()){
                long suchStringlong = Long.parseLong(suchString);
                if (kontakt.getNummern().contains(suchStringlong)){
                    model.addElement(kontakt.getName());
                    suchergebnisse.fuegeKontaktHinzu(kontakt);
                }
            }
        }
        suchergebnisse.alleKontakteAnzeigen();
        jListSuchergebnisse.setModel(model);
        jListSuchergebnisse.setVisible(true);
    }//GEN-LAST:event_jButtonSuchenActionPerformed

    //Anzeige Details eines Kontakts nach Suche in einer jList
    private void jListSuchergebnisseValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSuchergebnisseValueChanged
        // TODO add your handling code here:

        int index = 0;
                //Auswahl index
        index = jListSuchergebnisse.getSelectedIndex();
        System.out.println("index=" +index);

        //Kontakt auslesen
        Kontakt details = suchergebnisse.telefonbuchArray.get(index);
        Kontakt suchDetails = new Kontakt();
        suchDetails.setName(details.getName());
        suchDetails.setAdresse(details.getAdresse());
        suchDetails.setEmail(details.getEmail());
        suchDetails.setNummern(details.getNummern());
        //Textfelder befüllen
        jTextFieldSucheDetailsName.setText(suchDetails.getName());
        jTextFieldSucheDetailsAdresse.setText(suchDetails.getAdresse());
        jTextFieldSucheDetailsEmail.setText(suchDetails.getEmail());
        jTextFieldSucheDetailsNummer.setText(suchDetails.nummernToString());
    }//GEN-LAST:event_jListSuchergebnisseValueChanged

    //Lädt ein neues, leeres Telefonbuch und springt zu Alle Kontakte anzeigen
    private void butStartBuchNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStartBuchNeuActionPerformed
        // TODO add your handling code here:
        telefonbuch = new Telefonbuch();
        CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardAlleKontakteAnzeigen");
        menuKontakt.setEnabled(true);
    }//GEN-LAST:event_butStartBuchNeuActionPerformed

    
    private void butSucheZuruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSucheZuruckActionPerformed
        // TODO add your handling code here:
                CardLayout cl = (CardLayout) (cards.getLayout());
        ((java.awt.CardLayout) cl).show(cards, "cardAlleKontakteAnzeigen");
    }//GEN-LAST:event_butSucheZuruckActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiBuild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiBuild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiBuild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiBuild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiBuild().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alleKontakteAnzeigen;
    private javax.swing.JButton butCancelNeu;
    private javax.swing.JButton butKontaktLoeschen;
    private javax.swing.JButton butKontaktSpeichern;
    private javax.swing.JButton butKontaktSuchen;
    private javax.swing.JButton butSpeichernNeu;
    private javax.swing.JButton butStartBuchLaden;
    private javax.swing.JButton butStartBuchNeu;
    private javax.swing.JButton butSucheZuruck;
    private javax.swing.JButton butZusNummerNeu;
    private javax.swing.JPanel cards;
    private javax.swing.JLabel detailsAdresse;
    private javax.swing.JTextField detailsAdresseText;
    private javax.swing.JLabel detailsEmail;
    private javax.swing.JTextField detailsEmailText;
    private javax.swing.JLabel detailsName;
    private javax.swing.JTextField detailsNameText;
    private javax.swing.JLabel detailsNummer;
    private javax.swing.JButton jButtonSuchen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSucheDetailsName;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListSuchergebnisse;
    private javax.swing.JRadioButton jRadioButtonAdresse;
    private javax.swing.JRadioButton jRadioButtonEmailSuche;
    private javax.swing.JRadioButton jRadioButtonName;
    private javax.swing.JRadioButton jRadioButtonNummer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaNummern;
    private javax.swing.JTextField jTextFieldBeschreibungNeu;
    private javax.swing.JTextField jTextFieldSucheDetailsAdresse;
    private javax.swing.JTextField jTextFieldSucheDetailsEmail;
    private javax.swing.JTextField jTextFieldSucheDetailsName;
    private javax.swing.JTextField jTextFieldSucheDetailsNummer;
    private javax.swing.JPanel kontaktAnlegen;
    private javax.swing.JLabel labelAdresseNeu;
    private javax.swing.JLabel labelEMailNeu;
    private javax.swing.JLabel labelNameNeu;
    private javax.swing.JLabel labelNummerNeu;
    private javax.swing.JScrollPane listNamen;
    private javax.swing.JMenuItem menuAlleKontakteAnzeigen;
    private javax.swing.JMenuItem menuBeenden;
    private javax.swing.JMenu menuKontakt;
    private javax.swing.JMenuItem menuKontaktLoeschen;
    private javax.swing.JMenuItem menuKontaktSuchen;
    private javax.swing.JMenuItem menuLaden;
    private javax.swing.JMenuItem menuNeuerKontakt;
    private javax.swing.JMenuItem menuSpeichern;
    private javax.swing.JMenu menuTelefonbuch;
    private javax.swing.JMenuBar menueleiste;
    private javax.swing.JLabel neueBeschreibung2;
    private javax.swing.JLabel neueBeschreibung3;
    private javax.swing.JLabel neueBeschreibung4;
    private javax.swing.JLabel neueNummer2;
    private javax.swing.JLabel neueNummer3;
    private javax.swing.JLabel neueNummer4;
    private javax.swing.JPanel panelKontaktSuchen;
    private javax.swing.JPanel startWindow;
    private javax.swing.JTextField textFieldAdresseNeu;
    private javax.swing.JTextField textFieldNameNeu;
    private javax.swing.JTextField textFieldeMailNeu;
    private javax.swing.JTextField textSuche;
    private javax.swing.JTextField textfieldBeschreibung2;
    private javax.swing.JTextField textfieldBeschreibung3;
    private javax.swing.JTextField textfieldBeschreibung4;
    private javax.swing.JTextField textfieldNeueNummer2;
    private javax.swing.JTextField textfieldNeueNummer3;
    private javax.swing.JTextField textfieldNeueNummer4;
    private javax.swing.JTextField textfieldNummerNeu;
    private Telefonbuch telefonbuch;
    private Telefonbuch suchergebnisse;
    private Telefonnummer neueNummer;
    private int zusNummerCounter =0;
    private JOptionPane fehlermeldung;
    // End of variables declaration//GEN-END:variables
}
